name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  production:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      node-version: 14.x
      environment: production
    secrets: inherit
    permissions:
      id-token: write
      contents: read

  invalidate-cloudfront:
    needs: [production]
    uses: ./.github/workflows/invalidate-cloudfront.yml
    with:
      paths: "/*"
      environment: production
    secrets: inherit
    permissions:
      id-token: write
      contents: read
